#!/usr/bin/env python3
"""
Step 2: Crop figures from page exports using metadata from InDesign.

This script reads the figure_metadata.json file (generated by export-figure-metadata.jsx)
and crops each figure from the corresponding page export.

Usage:
    python3 crop_figures.py

Requirements:
    - Page exports in ~/Desktop/page_exports/ (run export-full-book-pages.jsx first)
    - Figure metadata in ~/Desktop/extracted_figures/figure_metadata.json
"""

import json
import os
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Installing Pillow...")
    os.system("pip3 install Pillow")
    from PIL import Image

# Configuration
METADATA_FILE = Path.home() / "Desktop/extracted_figures/figure_metadata.json"
PAGE_EXPORTS_DIR = Path.home() / "Desktop/page_exports"
OUTPUT_DIR = Path.home() / "Desktop/extracted_figures/cropped"

# InDesign uses 72 points per inch
# Our exports are at 150 DPI
# So conversion factor is 150/72 = 2.0833...
POINTS_TO_PIXELS = 150 / 72

def main():
    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Load metadata
    if not METADATA_FILE.exists():
        print(f"ERROR: Metadata file not found: {METADATA_FILE}")
        print("Run export-figure-metadata.jsx in InDesign first.")
        return
    
    with open(METADATA_FILE) as f:
        figures = json.load(f)
    
    print(f"Found {len(figures)} figures in metadata")
    
    # Process each figure
    exported = 0
    skipped = 0
    
    for i, fig in enumerate(figures):
        page_name = fig["page"]
        page_file = PAGE_EXPORTS_DIR / f"page_{page_name}.jpg"
        
        # Check if page export exists
        if not page_file.exists():
            # Try without leading zeros
            page_file = PAGE_EXPORTS_DIR / f"page_{page_name.lstrip('0') or '0'}.jpg"
            if not page_file.exists():
                print(f"  Skipping: page_{page_name}.jpg not found")
                skipped += 1
                continue
        
        # Load the page image
        try:
            img = Image.open(page_file)
        except Exception as e:
            print(f"  Error loading {page_file}: {e}")
            skipped += 1
            continue
        
        # Convert InDesign points to pixels
        # InDesign coordinates are in points from top-left of page
        left = int(fig["left"] * POINTS_TO_PIXELS)
        top = int(fig["top"] * POINTS_TO_PIXELS)
        right = int(fig["right"] * POINTS_TO_PIXELS)
        bottom = int(fig["bottom"] * POINTS_TO_PIXELS)
        
        # Ensure bounds are within image
        left = max(0, left)
        top = max(0, top)
        right = min(img.width, right)
        bottom = min(img.height, bottom)
        
        # Validate bounds
        if right <= left or bottom <= top:
            print(f"  Skipping invalid bounds for page {page_name}")
            skipped += 1
            continue
        
        # Crop
        try:
            cropped = img.crop((left, top, right, bottom))
        except Exception as e:
            print(f"  Error cropping: {e}")
            skipped += 1
            continue
        
        # Generate output filename
        image_name = fig.get("imageName", "unknown")
        # Clean filename
        safe_name = "".join(c if c.isalnum() or c in "._-" else "_" for c in image_name)
        output_file = OUTPUT_DIR / f"page_{page_name}_fig_{i+1}_{safe_name[:30]}.jpg"
        
        # Save
        cropped.save(output_file, quality=95)
        exported += 1
        
        if (i + 1) % 50 == 0:
            print(f"  Processed {i + 1}/{len(figures)} figures...")
    
    print(f"\nDone!")
    print(f"  Exported: {exported} figures")
    print(f"  Skipped: {skipped}")
    print(f"  Output: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()







