// AUTO-GENERATED by scaffold-system.ts
// Run: npx ignite scaffold
import type { JobExecutor } from "./types.js";
import { GeneratedIngestBook } from "./gen-ingest_book.js";
import { GeneratedExtractTokens } from "./gen-extract_tokens.js";
import { GeneratedExportCanonical } from "./gen-export_canonical.js";
import ExtractSkeleton from "./extract_skeleton.js";
import GenerateSection from "./generate_section.js";
import AssembleChapter from "./assemble_chapter.js";
import GenerateFigures from "./generate_figures.js";
import GenerateAiImages from "./generate_ai_images.js";
import InjectExistingFigures from "./inject_existing_figures.js";
import GenerateChapterRecap from "./generate_chapter_recap.js";
import ApplyBoxes from "./apply_boxes.js";
import ApplyErrata from "./apply_errata.js";
import ApplyMicrofix from "./apply_microfix.js";
import RenderChapterPdf from "./render_chapter_pdf.js";
import AssembleBook from "./assemble_book.js";
import GenerateIndex from "./generate_index.js";
import GenerateGlossary from "./generate_glossary.js";
import NormalizeVoice from "./normalize_voice.js";
import { GeneratedRenderBookPdf } from "./gen-render_book_pdf.js";
import { GeneratedValidateBook } from "./gen-validate_book.js";

export const JobRegistry: Record<string, JobExecutor> = {
  "ingest_book": new GeneratedIngestBook(),
  "extract_tokens": new GeneratedExtractTokens(),
  "export_canonical": new GeneratedExportCanonical(),
  "extract_skeleton": new ExtractSkeleton(),
  "generate_section": new GenerateSection(),
  "assemble_chapter": new AssembleChapter(),
  "generate_figures": new GenerateFigures(),
  "generate_ai_images": new GenerateAiImages(),
  "inject_existing_figures": new InjectExistingFigures(),
  "generate_chapter_recap": new GenerateChapterRecap(),
  "apply_boxes": new ApplyBoxes(),
  "apply_errata": new ApplyErrata(),
  "apply_microfix": new ApplyMicrofix(),
  "render_chapter_pdf": new RenderChapterPdf(),
  "assemble_book": new AssembleBook(),
  "generate_index": new GenerateIndex(),
  "generate_glossary": new GenerateGlossary(),
  "normalize_voice": new NormalizeVoice(),
  "render_book_pdf": new GeneratedRenderBookPdf(),
  "validate_book": new GeneratedValidateBook()
};
